#!/bin/bash

export LANDINGER_VERSION=v0.2
export LANDINGER_SHA1=becf37c7c2883c7c21e3e7c7a70b72122e3f081b
export LANDINGER_FOLDER=~/.landinger
export LANDINGER_JAR=$LANDINGER_FOLDER/landinger-$LANDINGER_VERSION.jar
export LANDINGER_URL=https://github.com/soywiz/landinger/releases/download/$LANDINGER_VERSION/landinger.jar
mkdir -p "$LANDINGER_FOLDER"

if ! test -f "$LANDINGER_JAR"; then
  if command -v wget > /dev/null 2>&1; then
    #echo "WGET"
    wget -q -O "$LANDINGER_JAR.temp" "$LANDINGER_URL"
  elif command -v curl > /dev/null 2>&1; then
    #echo "CURL"
    curl -s "$LANDINGER_URL" -o "$LANDINGER_JAR.temp"
  else
    echo "Can't find WGET or CURL"
  fi

    SHA1=$(shasum "${LANDINGER_JAR}.temp" | cut -d' ' -f1)
    if [ "$SHA1" == "$LANDINGER_SHA1" ]; then
      cp -f "${LANDINGER_JAR}.temp" "$LANDINGER_JAR"
      echo "DONE"
    else
      echo "Error downloading file: expected $LANDINGER_SHA1 but found $SHA1"
      exit 1
    fi
fi

java -jar "$LANDINGER_JAR" $*
