#!/usr/bin/env bash

SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

lsof -ti tcp:8080 | xargs kill 2> /dev/null

if [ "$*" == "" ]
then
$SCRIPTDIR/gradlew --project-dir=$SCRIPTDIR run
else
$SCRIPTDIR/gradlew --project-dir=$SCRIPTDIR run --args="$*"
fi
