#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPT")

lsof -ti tcp:8080 | xargs kill 2> /dev/null

if [ "$*" == "" ]
then
$SCRIPTDIR/gradlew run
else
$SCRIPTDIR/gradlew run --args="$*"
fi
